stable/storageos/Chart.yaml
stable/storageos/templates/daemonset_csi.yaml
stable/storageos/values.yaml

This updates the driver registrar container to support driver discovery
using kubelet plugin watcher.
It also updates the external provisioner and attacher to their latest
stable releases.
Bumping the chart version minor to 2 because the new driver registrar
will no longer work with kubernetes v1.11 and below without enabling
feature gate KubeletPluginsWatcher explicitly. This is in beta in k8s
v1.12 and is enabled by default.

storageos: Update CSI helpers to support new driver discovery

---

stable/storageoscluster-operator/Chart.yaml
stable/storageoscluster-operator/templates/operator.yaml
stable/storageoscluster-operator/values.yaml

StorageOS cluster operator command has been renamed to cluster-operator.
Change the same in pod spec of the deployment.

Operator: Change the container command

---

stable/storageos/Chart.yaml
stable/storageos/templates/secrets.yaml

CSI setup used to refer to the init-secret which was created
unconditionally. api-secret is created only for the non-CSI setup.
Since init-secret is removed now and api-secret has been moved to
the common namespace, it must be created always.

storageos/storageos: Create secrets for CSI as well

---

stable/storageos/Chart.yaml
stable/storageos/README-CSI.md

Adding a table to show what chart version should be used with what K8s version specifically for the CSI installation. 
Will only be merged once @darkowlzz updates the operator.

Add k8s chart version table

---

.travis.yml
test/ct.yaml

Removes the forked changes and uses the original repo with delete
release fix.
Refer: https://github.com/helm/chart-testing/issues/83

Use helmpack/chart-testing image with defer fix

---

stable/storageos/Chart.yaml
stable/storageos/README-CSI.md
stable/storageos/values.yaml

Updates the csi-provisioner container image with a forked version that
supports PVC labels.

storageos chart v1.0.0 with PVC labels support

---

stable/storageoscluster-operator/Chart.yaml
stable/storageoscluster-operator/README.md
stable/storageoscluster-operator/templates/NOTES.txt
stable/storageoscluster-operator/templates/job_crd.yaml
stable/storageoscluster-operator/templates/rbac.yaml
stable/storageoscluster-operator/templates/storageoscluster_crd.yaml
stable/storageoscluster-operator/templates/storageosupgrade_crd.yaml
stable/storageoscluster-operator/values.yaml

This sets chart version to 1.0.0 to avoid installing operator v1 if the previous version of the chart is updated.

StorageOS Operator v1 support

---

stable/storageoscluster-operator/Chart.yaml
stable/storageoscluster-operator/templates/job_crd.yaml
stable/storageoscluster-operator/templates/storageoscluster_crd.yaml
stable/storageoscluster-operator/templates/storageosupgrade_crd.yaml

`crd-install` helm hook ensures the CRDs are installed before a custom
resource.

cluster-operator: Add helm hook crd-install

---

stable/storageos/Chart.yaml
stable/storageos/LICENSE
stable/storageos/README-CSI.md
stable/storageos/ci/02-csi-values.yaml
stable/storageos/templates/csi_helpers.yaml
stable/storageos/templates/rolebinding.yaml
stable/storageos/templates/setup_csi.yaml
stable/storageos/templates/statefulset_csi.yaml
stable/storageos/values.yaml

This adds an option to deploy the CSI helper sidecars as Deployment,
keeping the default to StatefulSet.

storageos: Add CSI helper Deployment option

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/templates/storageoscluster_cr.yaml

The current storageos-cluster operator crd is missing the etcd TLS values if you want to use external etcd.

Add etcd TLS secret to operator crd

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/app-readme.md
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/cleanup.yaml
stable/storageos-operator/templates/rbac.yaml
stable/storageos-operator/templates/storageoscluster_cr.yaml
stable/storageos-operator/templates/storageoscluster_crd.yaml
stable/storageos-operator/values.yaml

Updates `storageos/storageos-operator` chart to be the same as `rancher/storageos-operator` chart.

storageos-operator: Sync with rancher chart

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/templates/cleanup.yaml

Fixes issue on cleanup by allowing deployments to be deleted by the cleanup user:
```
k -n storageos-operator logs storageos-csi-helper-cleanup-ssc8q 
Error from server (Forbidden): deployments.extensions "storageos-csi-helper" is forbidden: User "system:serviceaccount:storageos-operator:storageos-cleanup-sa" cannot delete resource "deployments" in API group "extensions" in the namespace "kube-system"
```

cleanup requires delete on deployments

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/questions.yml

Cleans up the form a bit to only show etcd tls options if both external etcd enabled and etcd tls.
After this I'll PR against the Rancher chart repo.

Hide etcd TLS if not enabled

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md

Looks like we need to install with at least helm 2.10 or we get an error `Error: apiVersion "storageos.com/v1" in storageos-operator/templates/storageoscluster_cr.yaml is not available`

Add a minimum helm version to README.md

---

stable/storageos-operator/Chart.yaml

`tillerVersion` enforces the version of helm supported by the chart.
Refer: https://helm.sh/docs/chart_best_practices/#restricting-tiller-by-version
Improves https://github.com/storageos/charts/pull/66

Set tillerVersion for supported helm version

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/questions.yml

Help text said to separate with semi-colons, should have said commas.

Fix help text for multiple kv endpoints

---

scripts/create-pr.sh
scripts/release.sh

Rancher charts dir structure changed to have separate directory for each
releases. This change modifies the release script to create the
appropriate dir structure and also sign-off the commits.
The requirements include, creating a base for the new release using the
existing latest release and committing it separately, and then adding
the changes for new release on top of the copied base as another commit.

Update rancher release for new dir structure

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/templates/cleanup.yaml
stable/storageos-operator/templates/storageoscluster_cr.yaml
stable/storageos-operator/values.yaml

Scheduler and pod-fencer resources are not cleaned up. This change adds
them in the cleanup resource list.
Also, adds conditionals around the tlsEtcdSecret configs to fix the validation errors (Rancher only):
```
validation failure list:
spec.tlsEtcdSecretRefNamespace in body must be of type string: "null"
spec.tlsEtcdSecretRefName in body must be of type string: "null"
```

improve cleanup & fix tlsEtcdSecret config validation

---

scripts/create-pr.sh

When git summary is big, it waits for keyboard input. Summary is not
needed.

create-pr: remove show summary statement

---

stable/storageos/Chart.yaml

storageos-operator chart will be the main chart.
Ref: [Deprecating Charts](https://github.com/helm/helm/blob/master/docs/charts.md#deprecating-charts)

Deprecate storageos chart

---

stable/storageoscluster-operator/Chart.yaml

storageos-operator will be the main chart.
Ref: [Deprecating Charts](https://github.com/helm/helm/blob/master/docs/charts.md#deprecating-charts)

Deprecate storageoscluster-operator chart

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/job_crd.yaml
stable/storageos-operator/templates/nfsserver_crd.yaml
stable/storageos-operator/templates/rbac.yaml
stable/storageos-operator/templates/storageoscluster_crd.yaml
stable/storageos-operator/templates/storageosupgrade_crd.yaml
stable/storageos-operator/values.yaml

Adds the new NFSServer CRD and new permissions for the same.
Also, updates the existing CRDs with generated definitions from the
operator repo.

Update to storageos-operator 1.4.0

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/templates/psp.yaml

API Group extensions/v1beta1 for PodSecurityPolicy is deprecated in
k8s 1.16. Use policy/v1beta1 API group. This was introduced in k8s
v1.10.
Rancher chart was already updated in https://github.com/rancher/charts/pull/237.
Refer: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16

Update PSP API group to policy/v1beta1

---

scripts/create-pr.sh
scripts/release.sh

[Rancher charts](https://github.com/rancher/charts) changed their default branch from `dev` to `master` and all the partners should submit their charts to the `partners` branch.
This change updates the create-pr.sh script to set upstream repo branch
against which the changes should be created for rancher charts.
Improvement: avoid creating second branch from an existing new branch.
Updated the [rancher fork's](https://github.com/darkowlzz/charts-2/) default branch to `master`.

create-pr: Set branch to create changes against

---

.travis.yml
stable/storageoscluster-operator/Chart.yaml
stable/storageoscluster-operator/templates/psp.yaml
test/e2e.sh

Update KinD to 0.6.0 and KinD node image to use k8s 1.16.3.
Also update charts-testing framework to v2.4.0.

Update KinD, k8s image & charts-testing framework

---

.travis.yml
scripts/release.sh
stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/rbac.yaml
stable/storageos-operator/values.yaml
test/e2e.sh

Also changes the rancher charts target branch to `master` because `partners` branch lacks the latest updates.

Update chart for cluster-operator 1.5.2

---

LICENSE
stable/storageos-operator/Chart.yaml
stable/storageos-operator/LICENSE
stable/storageos-operator/README.md
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/cleanup.yaml
stable/storageos-operator/templates/operator.yaml
stable/storageos-operator/values.yaml

- Updates node container to 1.5.3, use implicit image from operator
by default.
- Updates year in license
- Updates the cleanup permissions to add deployments, because the CSI
helpers can also be deployed as deployments.
- StorageOSCluster object should also be cleaned up when cleaning up a
cluster with auto-install. This is done by patching the custom resource
and removing the finalizer.
- Add conditionals around related images env vars. Conditionals help ensure that the env vars are not set when the image repo and tag are missing.

Update node container to 1.5.3 and permissions

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/app-readme.md
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/NOTES.txt
stable/storageos-operator/templates/_helpers.tpl
stable/storageos-operator/templates/cleanup.yaml
stable/storageos-operator/templates/operator.yaml
stable/storageos-operator/templates/rbac.yaml
stable/storageos-operator/templates/secrets.yaml
stable/storageos-operator/templates/storageoscluster_cr.yaml
stable/storageos-operator/templates/storageoscluster_crd.yaml
stable/storageos-operator/values.yaml
test/e2e.sh

- Defaults to StorageOS v2 install.
- Chart version: 0.3.0.
- Remove password generation because it's error prone. Regenerates upon update.
- CSI Resizer enabled by default.

Update chart to cluster-operator v2.1.0

---

.travis.yml
stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/crds/job_crd.yaml
stable/storageos-operator/crds/nfsserver_crd.yaml
stable/storageos-operator/crds/storageoscluster_crd.yaml
stable/storageos-operator/crds/storageosupgrade_crd.yaml
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/NOTES.txt
stable/storageos-operator/templates/operator.yaml
stable/storageos-operator/templates/secrets.yaml
stable/storageos-operator/values.yaml
test/ct.yaml
test/e2e.sh

- Update chart apiVerion to v2.
- Move CRDs to crds/ dir at the root of the chart.
- Remove crd-install hook annotation from the CRDs.
- Fix the typo in the cleanup manifest for namespace variable.
- Update charts-testing framework to v3.
- Remove tiller installation from e2e test.

Helm3 support

---

stable/storageos-operator/Chart.yaml

NOTE: Not updating the chart version to avoid publishing a new version. This change is a fix from the upstream review of the proposed changes.

Fix chart icon URI protocol to file

---

stable/storageos-operator/questions.yml

NOTE: Not updating the chart version to avoid publishing a new version. This change is based on the upstream review of the proposed changes.

rancher/questions: Set password as required

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/crds/storageoscluster_crd.yaml
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/operator.yaml
stable/storageos-operator/templates/rbac.yaml
stable/storageos-operator/values.yaml

- Update container image.
- Update CRD and RBAC.
- Add cleanup for api-manager deployment resources.
- Fix rancher charts unable to set etcd secrets.

helm3: Update to StorageOS v2.3.0

---

stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/operator.yaml
stable/storageos-operator/templates/rbac.yaml
stable/storageos-operator/templates/storageoscluster_crd.yaml
stable/storageos-operator/values.yaml

- Update container images.
- Update CRD and RBAC.
- Add cleanup for api-manager deployment resources.
- Fix rancher charts unable to set etcd secrets.

helm2: Update to StorageOS v2.3.0

---

scripts/release.sh

Rancher charts should be moved into charts/ dir in the upstream rancher
charts repo. This changes `UPSTREAM_CHART_PATH` parameter of the
create-pr.sh script to the new path, `charts`.
Refer: https://github.com/rancher/charts/pull/811#pullrequestreview-531605137

helm2: Change the rancher charts target path

---

.circleci/config.yml

Should be re-enabled after https://github.com/helm/helm/pull/9416 merges
and included in a Helm release.

Disable the Helm chart linter

---

.circleci/config.yml
.travis.yml
stable/storageos-operator/Chart.yaml
stable/storageos-operator/README.md
stable/storageos-operator/app-readme.md
stable/storageos-operator/questions.yml
stable/storageos-operator/templates/rbac.yaml
stable/storageos-operator/values.yaml
test/ct.yaml
test/e2e.sh

Bumps to v2.4.0.  Tested on Rancher.
Includes changes that were intended for v2.3.3 but weren't merged due to the Helm linter issue which is now resolved.

helm3: Update to StorageOS v2.4.0
